### ISSUE TITLE
Uploading Base64 image string

### ISSUE THREAD

**Issue by milesmatthias** [assembler/attachinary#105]
Hi all. Great gem!

I have a slightly different use case and haven't seen it addressed anywhere, so I thought I'd ask. I use a canvas element to allow a user to give us their signature, which is sent to me in a Base64 data string:

```
"data:image/png;base64,iVBORw0KG..."
```

I've seen that I can do something like:

```ruby
sig_uri = URI::Data.new(@signature_data)
File.write('tmp/signature.jpg', sig_uri.data)
@record.signature = File.open('tmp/signature.jpg', 'r')
```

where `@record.signature` is an attachinary attachment. But do you have an other suggestions? Is there a way I could avoid writing to a temporary file? I suppose I could upload it directly from the browser.

**Comment by milesmatthias** [comment]
I've got this working like the above code snippet, but I'm wondering how soon I can remove the temporary file. Can I remove the tmp file after saving the record, or immediately? When does the actual upload happen?

**Comment by tocker** [comment]
The resource is uploaded immediately upon assignment. You can safely remove the temp file afterwards.

**Comment by milesmatthias** [comment]
Thanks @tocker!

**Comment by tersor** [comment]
Cloudinary supports [uploading Base64 strings](https://support.cloudinary.com/hc/en-us/articles/203125741-Can-I-upload-using-DATA-URI-BASE64-).

Ugly hack avoid saving the file:

```ruby
upload = Attachinary::Utils.process_hash(Cloudinary::Uploader.upload(@signature_data))
upload.scope = 'signature'
@record.signature = upload
```
