### ISSUE TITLE
Record browser direct image upload in DB

### ISSUE THREAD

**Issue by milesmatthias** [assembler/attachinary#108]
I'm using attachinary for admin uploads, but on our user facing web client, the browser directly uploads an image to clourindary, so I already have the cloudinary id for the upload.

I know I can use [this patch](https://github.com/spitzer/attachinary/commit/d65f15e26844c4253e8359d5c2b750a50f52afbd) and do something like:

```ruby
model.upload_url = "http://res.cloudinary.com/upload.jpg"
```

but that triggers another upload. Is there something like:

```ruby
model.upload_cloudinary_public_id = "sadkjf1k3kjsdj1"
```

? Thanks.

**Comment by milesmatthias** [comment]
Any ideas @assembler?

**Comment by tocker** [comment]
Hi @milesmatthias,

Please check the dummy project's form [code](https://github.com/assembler/attachinary/blob/master/spec/dummy/app/views/notes/_form_builder.html.erb#L12-15) for an example of direct upload.

If your use case requires a manual update of the public_id, assign a hash of the values to the attachinary member:

```ruby
model.upload = { "public_id" => "sadkjf1k3kjsdj1" ... }
```
**Warning:** this will delete the previously attached resource if one existed.

If you want to update an existing resource, just use `update_attributes`:

```ruby
model.upload.update_attribute :public_id, "sadkjf1k3kjsdj1"
```

**Comment by milesmatthias** [comment]
Thanks @tocker!

**Comment by milesmatthias** [comment]
@tocker Sorry, I don't think this solves my issue just yet. When I said direct upload, I didn't mean using your direct upload helper. I've seen that, and it works fine for when Rails is writing the views, but when a JS MVC application is creating the file upload inputs, I'm using Cloudinary's unsigned uploads: http://cloudinary.com/blog/direct_upload_made_easy_from_browser_or_mobile_app_to_the_cloud

So the model doesn't have an attachinary upload at all yet, but I do have a url of the upload. Can I initialize a new attachment with a public id without triggering a new upload?

**Comment by milesmatthias** [comment]
@tocker could I do something like this:

```ruby
model.upload = Attachinary::File.new({
  :version       => "123123123123",
  :public_id     => "asdkfljsdkfjsd",
  :resource_type => "jpg"
})
```

?

**Comment by milesmatthias** [comment]
If anyone else sees this, I was able to do what I need by doing something like this:

```ruby
model.upload = Attachinary::File.new({
  :version              => "123456",
  :public_id            => "askdjfslkdjflksd",
  :resource_type        => "image",
  :attachinariable_type => "ModelName",
  :scope                => "upload",
  :format               => "png"
})
```

**Comment by tocker** [comment]
Glad to hear your issue is resolved.

**For reference**: upload is triggered when assigning a value to `model.resource_url` (where "`resource`" is whatever you named the attachment, ie "`upload`"), or when assigning an input stream to `model.resource`. 

Normally the browser passes the JSON object returned from the Cloudinary API as a string. When this string is assigned to `model.resource`, Attachinary implicitly creates a new  `Attachinary::File` - as you did explicitly.

Thus you can achieve the same affect by (note that `attachinariable_type` and `scope` are not required):

``` ruby
model.upload = {
  :version       => "123456",
  :public_id     => "askdjfslkdjflksd",
  :resource_type => "image",
  :format        => "png"
}

# or

model.upload = '{"version":"123456","public_id":"askdjfslkdjflksd","resource_type":"image","format":"png"}'

```

**Comment by milesmatthias** [comment]
Ah, perfect @tocker. That's exactly what I was looking for. I'll submit you a PR for the README for others using Cloudinary's new unsigned uploads feature. Thanks!
