### ISSUE TITLE
Support for Cloudinary 1.1.0

### ISSUE THREAD

**Issue by jfeust** [assembler/attachinary#111]
I just added these:

    gem 'cloudinary'
    gem 'attachinary'

Did `bundle install`

And got:

    Bundler could not find compatible versions for gem "cloudinary":
        In Gemfile:
          attachinary (>= 0) ruby depends on
              cloudinary (~> 1.0.24) ruby

          cloudinary (1.1.0)

**Comment by tocker** [comment]
Updated Gemfile.
Can you please retest?

**Comment by jfeust** [comment]
Yes, pulling the gem directly from the repo let's me include cloudinary 1.1.0.  So that looks good.

    gem 'cloudinary', '~>1.1.0'
    gem 'attachinary', git: "https://github.com/assembler/attachinary.git"

**Comment by ssaunier** [comment]
Seems like the latest version of `attachinary` (`1.3.1`) fixes this problem, issue might be closed.

**Comment by thedrow** [comment]
@tocker @jfeust Can you close the issue?
