### ISSUE TITLE
responders gem required

### ISSUE THREAD

**Issue by dmilisic** [assembler/attachinary#120]
I got the following error with rails 4.2.4

````
/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/mime_responds.rb:10:in `respond_to': The controller-level `respond_to' feature has been extracted to the `responders` gem. Add it to your Gemfile to continue using this feature: (NoMethodError)
  gem 'responders', '~> 2.0'
Consult the Rails upgrade guide for details.
````

Maybe the `responders` gem should be added as a dependency?

**Comment by dmilisic** [comment]
It seems that 2 pull requests for this feature already exist (#112 & #117)

**Comment by orlando** [comment]
@dmilisic #112 was merged, you can use master for now, until a new version is released

**Comment by dmilisic** [comment]
thanks

**Comment by johnnymugs** [comment]
Thanks for this gem and for this fix! Any plans to release a new version soon?
