### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/assets/cloudinary/cloudinary-jquery-file-upload.js.map"):

### ISSUE THREAD

**Issue by NQuinn27** [assembler/attachinary#128]
i am getting this error when uploading an image. I followed the instructions in the readme, and everything seems to be in order.

The images are being stored on cloudinary, but along with the above error, the saved urls are incorrect, example: http://res.cloudinary.com/haf08o9io/image/upload/%23%3CAttachinary::File:0x007ff2d2589130%3E

This is in development environment

**Comment by mihizi** [comment]
hey! Would you happen to remember how you resolved this issue?
