### ISSUE TITLE
Dependency on old version of cloudinary gem

### ISSUE THREAD

**Issue by ssaunier** [assembler/attachinary#133]
Hello,

I noticed that the last `attachinary` release (1.3.1, Oct 4th 2015) is locking the `cloudinary` gem to the version `1.1.0`. Is there incompatibilities with latest cloudinary gem version (1.2.2)?

Do you plan on releasing a new version?

Thanks!

**Comment by khelal** [comment]
+1. Just had the same problem.

**Comment by ghost** [comment]
+1, same problem here

**Comment by mklb** [comment]
Quickfix: https://github.com/assembler/attachinary/issues/147#issuecomment-347112962

**Comment by ssaunier** [comment]
Thanks @mklb for the quick fix. Last commit on this gem is 4 years old, I think we can consider it dead for now.
