### ISSUE TITLE
Custom styling and supressing image preview

### ISSUE THREAD

**Issue by kbaum** [assembler/attachinary#69]
Because I am using cloudinary for raw attachments, i do not need to show the image preview.  I also need to completely style the look and feel of the file upload and the remove link:

http://grab.by/pkNO

Is it possible to suppress the image preview with the attachinary file uploader javascript?  I imagine i could get all of this done by hiding the elements with css.

The other question i have is that i am not sure that it even makes sense for me to use the attachinary js widget.  I need the ability to:

1)  upload multiple files
2)  upload directly from the browser
3)  drag and drop files into the uploader
4)  see some type of progress bar when attaching files

Does it make sense to use attachinary or something else like jquery.cloudinary?  

thx!

**Comment by 90caiosantos** [comment]
hey Kbaum, this directory Attachinary was not created in my app, where do i change that?

**Comment by kbaum** [comment]
Not sure what you mean.

**Comment by 90caiosantos** [comment]
Sorry man, i edited my last comment.

**Comment by kbaum** [comment]
@90caiosantos - attachinary.js comes from the gem and rails should find it as it will look in all vendor directories.

**Comment by 90caiosantos** [comment]
thats how attachinary looks like in my app using:

<%= f.attachinary_file_field :photos %>


thats how it supposeto look?

![attachinary](https://cloud.githubusercontent.com/assets/7756434/7443028/22251810-f104-11e4-8ddd-885aa9925821.jpg)

**Comment by kbaum** [comment]
Don't remember honestly.  Are there any stylesheets that come with attachinary? Are they getting applied?

**Comment by mikemerritt** [comment]
@90caiosantos Did you ever figure out how to get the proper aspect ratio for the image?

**Comment by orlando** [comment]
@mikemerritt what you can do is set the preview to crop, as @kbaum said you can change the template by changing the jquery attachinary plugin config

This is what I have in my app:

```js
$.attachinary.config.template = '\
  <ul>\
    <% for(var i=0; i<files.length; i++){ %>\
      <li>\
        <% if(files[i].resource_type == "raw") { %>\
          <div class="raw-file"></div>\
        <% } else { %>\
          <img\
            src="<%= $.cloudinary.url(files[i].public_id, { "version": files[i].version, "format": "jpg", "crop": "fill", "width": 250, "height": 250 }) %>"\
            alt="" width="100" height="100" />\
        <% } %>\
        <a href="#" data-remove="<%= files[i].public_id %>"><i class="md md-clear md-2x"></i></a>\
      </li>\
    <% } %>\
  </ul>\
';
```

Notice the configuration and how I change the size, also I put a bigger image in a smaller container to get the "2x" rendering feel.

**Comment by orlando** [comment]
@90caiosantos attachinary doesn't include styles for the image preview, you have to do this yourself.

![gif](http://g.recordit.co/T2R21k7zY6.gif)

**Comment by cosydney** [comment]
hi @orlando , they way you styled it is pretty cool, would you mind sharing the stylesheet ?

**Comment by orlando** [comment]
@cosydney Sure, here is https://gist.github.com/orlando/2416c754572b3d51a31ee008f6cb4a14. There are some variables like `$space`, but you should be able to customize it to your needs.

**Comment by cosydney** [comment]
Wow thanks for the quick response ! As I was waiting I did something where I played with the css and X : 

<img width="899" alt="capture d ecran 2016-08-10 08 19 22" src="https://cloud.githubusercontent.com/assets/10532381/17545117/2de61904-5ed3-11e6-80cd-79d3d04657d9.png">

**Comment by orlando** [comment]
@cosydney Great, glad it worked for you
