### ISSUE TITLE
Upload progress bar not shown etc.

### ISSUE THREAD

**Issue by Michel1975** [assembler/attachinary#77]
Hi,
I just signed for a Cloudinary account and downloaded this gem for my rails project.I am a total newbie when it comes to advanced Jquery so please bear with me.

I followed all the setup instructions and basic file uploading works fine. However, the upload progress bar is not shown during upload. 

Do I need to setup this manually because according to recent release notes this should work out of the box?

![image](https://f.cloud.github.com/assets/1773267/1274987/f2af8d80-2ddd-11e3-86a9-4a7ac30f6e8b.png)

I also noticed that a "No file has been selected" message is shown next to the file upload box during upload. Is there any way to get rid of this?

I would also like to display preview images in a separate div-container instead of ul lists. Can you explain how to set this up using templates?

Thanks.

BR
Michel

**Comment by milesmatthias** [comment]
Nothing is showing for me either.

@xhanix I see https://github.com/assembler/attachinary/blob/master/lib/assets/javascripts/attachinary.js.coffee#L109, but nothing is shown in the UI. What needs to be done to show _something_?

**Comment by bbnnt** [comment]
+1
