### ISSUE TITLE
Adding more photos via update_attributes

### ISSUE THREAD

**Issue by dwowen** [assembler/attachinary#81]
I'm not sure the proper way to add more photos to an existing model that has 'has_attachments' set, but after successfully uploading images with 'create', adding more photos via update_attributes overrides and deletes existing photos before setting the new photos

Is there a correct way for doing this? I can post code, but I'm not doing anything fancy, just using a simple form_for.

**Comment by jasonwc** [comment]
+1. Would love the option to add additional photos without losing the ones already uploaded.
