### ISSUE TITLE
Cannot load coffee_script

### ISSUE THREAD

**Issue by JESii** [assembler/attachinary#82]
Just upgraded to Rails 2.0, installed cloudinary and attachinary; I believe I have completed all installation instructions. However, I get the following error when starting my rails app:

```
cannot load such file -- coffee_script
  (in /home/jseidel/.rvm/gems/ruby-2.0.0-p247/gems/attachinary-1.2.6/lib/assets/javascripts/attachinary.js.coffee)
```

That file (attachinary.js.coffee) is nowhere to be found in my app... what am I missing here?

**Comment by birdjonathan** [comment]
Still an issue with rails 4.0+, it would be great to add the 'coffee-rails' gem to the requirements list.
